name: Retrain Every 3 Days

on:
  schedule:
    - cron: "0 7 */3 * *"  # รันเวลา 07:00 UTC (ประมาณ 14:00 ไทย) ทุก 3 วัน
  workflow_dispatch:       # เผื่ออยากกดรันเองด้วย

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install pipreqs + core dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipreqs
        pip install -r requirements.txt || true

    - name: Auto-update requirements.txt
      run: |
        pipreqs . --force
        echo "Updated requirements.txt"

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install "optimum[intel]" mlflow

    - name: Run MLOps pipeline (retrain)
      run: |
        python mlops/pipeline.py
