name: Retrain and Deploy Every 6 hour

on:
  # schedule:
  #   - cron: '0 */6 * * *' #retrain ทุก 6 ชม
  workflow_dispatch:

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install "optimum[intel]" mlflow boto3

    - name: Run MLOps pipeline
      run: |
        python mlops/pipeline.py

    - name: Trigger deploy workflow
      uses: peter-evans/repository-dispatch@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        event-type: mlflow_prod_trigger
        client-payload: '{"model_uri": "s3://modelmlops/Model/model.tar.gz"}'
