name: Auto Train + Compress + Log to MLflow

on:
  push:
    branches: [main]         # รันเมื่อมี push ไปที่ main
  workflow_dispatch:         # ให้สามารถกดรันเองได้จาก GitHub UI

jobs:
  train-and-log:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install pipreqs + core dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipreqs
        pip install -r requirements.txt || true  # บางอันอาจยังไม่เคยมี

    - name: Auto-generate updated requirements.txt
      run: |
        pipreqs . --force
        echo " Updated requirements.txt based on actual imports"

    - name: Install project dependencies
      run: |
        pip install -r requirements.txt
        pip install "optimum[intel]" mlflow

    - name: Run MLOps pipeline
      run: |
        python mlops/pipeline.py

